---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/mizu version
    register: mizu_test_output
  - name: mizu version
    debug:
      msg: '{{ mizu_test_output.stderr }}'
